//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eEdir_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eEdirManagementSystemDBEntities : DbContext
    {
        public eEdirManagementSystemDBEntities()
            : base("name=eEdirManagementSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblMember> tblMembers { get; set; }
        public virtual DbSet<tblMemberFamily> tblMemberFamilies { get; set; }
        public virtual DbSet<tblMemberNotification> tblMemberNotifications { get; set; }
        public virtual DbSet<tblMemberPayment> tblMemberPayments { get; set; }
        public virtual DbSet<tblNotificationType> tblNotificationTypes { get; set; }
        public virtual DbSet<tblPaymentPeriod> tblPaymentPeriods { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblRelationType> tblRelationTypes { get; set; }
        public virtual DbSet<tblSubcity> tblSubcities { get; set; }
        public virtual DbSet<tblWoreda> tblWoredas { get; set; }
    }
}
