//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eEdir_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberFamily
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string Fullname { get; set; }
        public int RegionID { get; set; }
        public Nullable<int> SubcityID { get; set; }
        public Nullable<int> WoredaID { get; set; }
        public string HouseNumber { get; set; }
        public string PhoneNumber { get; set; }
        public int RelationTypeID { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblRegion tblRegion { get; set; }
        public virtual tblRelationType tblRelationType { get; set; }
        public virtual tblSubcity tblSubcity { get; set; }
        public virtual tblWoreda tblWoreda { get; set; }
    }
}
