//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eEdir_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMember()
        {
            this.tblMemberFamilies = new HashSet<tblMemberFamily>();
            this.tblMemberNotifications = new HashSet<tblMemberNotification>();
            this.tblMemberPayments = new HashSet<tblMemberPayment>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public int RegionID { get; set; }
        public int SubcityID { get; set; }
        public int WoredaID { get; set; }
        public string HouseNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime MembershipDate { get; set; }
    
        public virtual tblRegion tblRegion { get; set; }
        public virtual tblSubcity tblSubcity { get; set; }
        public virtual tblWoreda tblWoreda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberFamily> tblMemberFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberNotification> tblMemberNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberPayment> tblMemberPayments { get; set; }
    }
}
